// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tuuheltuhughlrqlqocp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1dWhlbHR1aHVnaGxycWxxb2NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMjk5MjcsImV4cCI6MjA2NTgwNTkyN30.9pWCdmQR_ss4MgiUOlTuJLvKj-kWM1sbvbV5j4q4xEM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);